name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  lint:
    name: Lint with ESLint / Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Run ESLint
        run: |
          npm install
          npm run lint
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Patch sonar.properties
        run: sed -i s/\$VERSION/$(jq -r .version package.json)/ sonar-project.properties
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  test:
    name: Integration tests
    strategy:
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-10.15, windows-2019 ]
        version: [ latest, local, 245.0.0 ]
        project: [ auto, windys-lab ]
        exclude:
          - os: macos-10.15
            version: local
          - os: windows-2019
            version: local
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Google Cloud SDK
        uses: ./
        with:
          version: ${{ matrix.version }}
          project: ${{ matrix.project }}
          components: beta
          service-account-key: ${{ secrets.GCLOUD_AUTH }}
      - name: Test Google Cloud SDK CLI
        run: |
          gcloud version
          gcloud config list account --format "value(core.account)"
